In [2]:
import pandas as pd
data = pd.read_csv("/content/SMSSpamCollection", sep='\t', names=["label", "message"])
data.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
#nltk libraries

import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


In [ ]:
import re #regular expression
stemmer = PorterStemmer()
corpus = [] # corpus list

for i in range(0, len(data)):
    rev = re.sub('[^a-zA-Z]', ' ', data['message'][i])
    rev = rev.lower()
    rev = rev.split()
    rev = [stemmer.stem(word) for word in rev if not word in set(stopwords.words('english'))]
    rev = ' '.join(rev)
    corpus.append(rev)

In [ ]:
corpus[:10]

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free']

In [ ]:

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000)
X = cv.fit_transform(corpus).toarray()

In [ ]:

y = pd.get_dummies(data['label'])
y = y.iloc[:,1].values

array([False, False,  True, ..., False, False, False])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [ ]:

from sklearn.naive_bayes import ComplementNB

spam_detect_model = ComplementNB().fit(X_train, y_train)

In [ ]:
pred = spam_detect_model.predict(X_test)

In [ ]:

pred

array([False, False,  True, ...,  True, False, False])

In [ ]:

from sklearn.metrics import confusion_matrix
confusion_m = confusion_matrix(y_test, pred)

In [ ]:
confusion_m

array([[917,  54],
       [  7, 137]])

In [ ]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test, pred)
acc

0.9452914798206278


***word 2 vec***

In [ ]:
pip install gensim

In [ ]:
import nltk
nltk.download('punkt')
from gensim.models import Word2Vec
from nltk.corpus import stopwords

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
nltk.download('stopwords')

In [ ]:
paragraph = """
              Mahendra Singh Dhoni (/məˈheɪndrə ˈsɪŋ dhæˈnɪ/ ⓘ; born 7 July 1981) is an Indian professional cricketer who plays as a right-handed batter and a wicket-keeper. Widely regarded as one of the most prolific wicket-keeper batsmen and captains, he represented the Indian cricket team and was the captain of the side in limited overs formats from 2007 to 2017 and in test cricket from 2008 to 2014. Dhoni has captained the most international matches and is the most successful Indian captain. He has led India to victory in the 2007 ICC World Twenty20, the 2011 Cricket World Cup, and the 2013 ICC Champions Trophy, being the only captain to win three different limited overs ICC tournaments. He also led the teams that won the Asia Cup in 2010, 2016 and was a member of the title winning squad in 2018.
              """

In [ ]:
import re

text = re.sub(r'\s+', ' ', paragraph)
text = text.lower()
text = re.sub(r'\d', ' ', text)
text = re.sub(r'\s+', ' ', text)

In [ ]:
sentences = nltk.sent_tokenize(text)

sentences = [nltk.word_tokenize(sentence) for sentence in sentences]

for i in range(len(sentences)):
    sentences[i] = [word for word in sentences[i] if word not in stopwords.words('english')]

In [ ]:
sentences

[['mahendra',
  'singh',
  'dhoni',
  '(',
  '/məˈheɪndrə',
  'ˈsɪŋ',
  'dhæˈnɪ/',
  'ⓘ',
  ';',
  'born',
  'july',
  ')',
  'indian',
  'professional',
  'cricketer',
  'plays',
  'right-handed',
  'batter',
  'wicket-keeper',
  '.'],
 ['widely',
  'regarded',
  'one',
  'prolific',
  'wicket-keeper',
  'batsmen',
  'captains',
  ',',
  'represented',
  'indian',
  'cricket',
  'team',
  'captain',
  'side',
  'limited',
  'overs',
  'formats',
  'test',
  'cricket',
  '.'],
 ['dhoni',
  'captained',
  'international',
  'matches',
  'successful',
  'indian',
  'captain',
  '.'],
 ['led',
  'india',
  'victory',
  'icc',
  'world',
  'twenty',
  ',',
  'cricket',
  'world',
  'cup',
  ',',
  'icc',
  'champions',
  'trophy',
  ',',
  'captain',
  'win',
  'three',
  'different',
  'limited',
  'overs',
  'icc',
  'tournaments',
  '.'],
 ['also',
  'led',
  'teams',
  'asia',
  'cup',
  ',',
  'member',
  'title',
  'winning',
  'squad',
  '.']]

In [ ]:
# Training the Word2Vec model
model = Word2Vec(sentences, min_count=1) #skip word if less than count 1

In [ ]:
model.wv.words_closer_than('cricket', 'member')

<ipython-input-54-1456c9b85ddd>:1: DeprecationWarning: Call to deprecated `words_closer_than` (Use closer_than instead).
  model.wv.words_closer_than('cricket', 'member')


['.',
 'icc',
 'indian',
 'captain',
 'world',
 'cup',
 'wicket-keeper',
 'overs',
 'limited',
 'dhoni',
 'plays',
 'regarded',
 'batter',
 'right-handed',
 'widely',
 'squad',
 'cricketer',
 'batsmen',
 ')',
 'july',
 'born',
 ';',
 'ⓘ',
 'dhæˈnɪ/',
 'ˈsɪŋ',
 '/məˈheɪndrə',
 'singh',
 'team',
 'captains',
 'champions',
 'title',
 'asia',
 'teams',
 'also',
 'tournaments',
 'different',
 'three',
 'win',
 'twenty',
 'represented',
 'victory',
 'india',
 'successful',
 'matches',
 'captained',
 'test',
 'formats',
 'side',
 'winning',
 'mahendra']

## ***Fake News Detection***

In [4]:
pip install keras

In [8]:
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
from tensorflow.keras.utils import to_categorical

# Download necessary NLTK data
nltk.download('stopwords')
nltk.download('punkt')
stop_words = set(stopwords.words('english'))


data = pd.read_csv('/content/train.csv')
data = data[['text', 'label']]


data['text'] = data['text'].fillna('')


def preprocess_text(text):
    text = text.lower()
    text = nltk.word_tokenize(text)
    text = [word for word in text if word.isalnum()]
    text = [word for word in text if word not in stop_words]
    return " ".join(text)


data['text'] = data['text'].apply(preprocess_text)


label_encoder = LabelEncoder()
data['label'] = label_encoder.fit_transform(data['label'])


X_train, X_test, y_train, y_test = train_test_split(data['text'], data['label'], test_size=0.2, random_state=42)

tokenizer = Tokenizer(num_words=5000)
tokenizer.fit_on_texts(X_train)
X_train = tokenizer.texts_to_sequences(X_train)
X_test = tokenizer.texts_to_sequences(X_test)


maxlen = 100
X_train = pad_sequences(X_train, padding='post', maxlen=maxlen)
X_test = pad_sequences(X_test, padding='post', maxlen=maxlen)


y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

# Build the LSTM model
model = Sequential()
model.add(Embedding(input_dim=5000, output_dim=128, input_length=maxlen))
model.add(LSTM(units=128, return_sequences=False))  # LSTM layer
model.add(Dropout(0.5))
model.add(Dense(2, activation='softmax'))  # Output layer (2 classes: Fake and Real)


model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


model.fit(X_train, y_train, batch_size=64, epochs=5, validation_data=(X_test, y_test))


loss, accuracy = model.evaluate(X_test, y_test)
print(f'Test Accuracy: {accuracy * 100:.2f}%')


model.save('fake_news_detection_lstm.h5')


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Epoch 1/5
260/260 ━━━━━━━━━━━━━━━━━━━━ 74s 273ms/step - accuracy: 0.7864 - loss: 0.4489 - val_accuracy: 0.9154 - val_loss: 0.2219
Epoch 2/5
260/260 ━━━━━━━━━━━━━━━━━━━━ 79s 260ms/step - accuracy: 0.9414 - loss: 0.1700 - val_accuracy: 0.8913 - val_loss: 0.2961
Epoch 3/5
260/260 ━━━━━━━━━━━━━━━━━━━━ 71s 274ms/step - accuracy: 0.9453 - loss: 0.1545 - val_accuracy: 0.9200 - val_loss: 0.2325
Epoch 4/5
260/260 ━━━━━━━━━━━━━━━━━━━━ 76s 292ms/step - accuracy: 0.9673 - loss: 0.1014 - val_accuracy: 0.9132 - val_loss: 0.3045
Epoch 5/5
260/260 ━━━━━━━━━━━━━━━━━━━━ 68s 261ms/step - accuracy: 0.9801 - loss: 0.0696 - val_accuracy: 0.9187 - val_loss: 0.2535
130/130 ━━━━━━━━━━━━━━━━━━━━ 8s 56ms/step - accuracy: 0.9171 - loss: 0.2592


Test Accuracy: 91.87%
